profiles:

  apollo:
  - common
  - host

  cronus:
  - common
  - mac
  - macserver

  devcontainer:
  - common

  hermes:
  - common
  - host
  - winlinux

  zeus:
  - common
  - host
  - mac
  - macworkstation

