profiles:

  apollo:
  - common
  - host

  cronus:
  - common
  - mac
  - macserver

  devcontainer:
  - common

  wsl:
  - common
  - host
  - winlinux

  zeus:
  - common
  - host
  - mac
  - macworkstation

  pinas:
  - pinas

